#define HUMIDITY_ONE 0
#define HUMIDITY_TWO 2
#define TEMPERATURE 3


/*Virtuales*/

#define HOUR_ONE 16
#define TIME_SPAN_ONE 17
#define HOUR_TWO 18
#define TIME_SPAN_TWO 19
#define HOUR_THREE 20
#define TIME_SPAN_THREE 21
#define HOUR_FOUR 22
#define TIME_SPAN_FOUR 23

#define HUMIDITY_ONE_LIMIT_H 24
#define HUMIDITY_ONE_LIMIT_L 25
#define HUMIDITY_TWO_LIMIT_H 26
#define HUMIDITY_TWO_LIMIT_L 27
#define HUMIDITY_THREE_LIMIT_H 28
#define HUMIDITY_THREE_LIMIT_L 29
#define HUMIDITY_FOUR_LIMIT_H 30
#define HUMIDITY_FOUR_LIMIT_L 31