

#define READ_OUTPUT_TABLE (1)
#define READ_INPUT_TABLE (2)
#define READ_REGISTERS (3)
#define READ_ANALOG_INPUTS (4)
#define FORCE_SINGLE_OUTPUT (5)
#define PRESET_SINGLE_REGISTER (6)
#define READ_EXCEPTION_STATUS (7)
#define LOOPBACK (8)
#define FORCE_MULTIPLE_OUTPUTS (15)
#define PRESET_MULTIPLE_REGISTERS (16)
#define REPORT_DEVICE_TYPE (17)
#define READ_SCRATCH_PAD (67)

