
export CPATH=../include

CC= powerpc-linux-g++ -I/usr/local/include

DIR=ppc/

$(DIR)%.o:      %.cpp $(INCLUDES)
	$(CC) -c -fpic -o $@ -Wall $<

$(DIR)librtcommon.so: $(DIR)arg.o $(DIR)common.o $(DIR)safestr.o $(DIR)utimer.o $(DIR)memfail.o
	$(CC) -shared -o $(DIR)librtcommon.so $(DIR)arg.o $(DIR)common.o $(DIR)safestr.o $(DIR)utimer.o $(DIR)memfail.o

install:
	cp $(DIR)librtcommon.so /opt/sixnet/lib/gcc-lib/powerpc-linux/2.95.3/

clean:
	rm -fv $(DIR)*.o $(DIR)*.so


