# Makefile for react.

all:

install:
	mkdir -p /usr/local/etc/react2/web
	cp webserver.js /usr/local/etc/react2/web/
	cp -r ../svg /usr/local/etc/react2/

uninstall:
	rm -rf /usr/lcoal/etc/react2/web
	rm -rf /usr/local/etc/react2/svg
